# Generated by Django 3.0.4 on 2020-04-01 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_authors_journals_results'),
        ('users', '0002_remove_customuser_bibgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bibgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.Bibgroup'),
        ),
    ]
