# Generated by Django 3.0.4 on 2020-04-01 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20200401_1401'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ADStest',
        ),
    ]
