# Generated by Django 3.0.4 on 2020-04-03 18:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20200401_1149'),
        ('search', '0009_result_bibgroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Result',
            new_name='Report',
        ),
    ]
