# Generated by Django 3.0.4 on 2020-04-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_auto_20200413_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryreport',
            name='daterange',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
